import { createClient } from '@/lib/supabase/server';

export interface GeneratedSkill {
  id: string;
  name: string;
  code: string;
  description?: string;
  version: 'v0' | 'v1' | 'v2';
  created_at: string;
  user_id?: string;
}

const SKILLS_DIR = 'src/lib/mcp/skills';

export function normalizeSkillName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^[0-9]/, '');
}

export async function saveSkill(skill: Omit<GeneratedSkill, 'id' | 'created_at'>): Promise<GeneratedSkill> {
  const fs = await import('fs');
  const path = await import('path');
  
  const dir = path.join(process.cwd(), SKILLS_DIR);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  
  const filename = `${normalizeSkillName(skill.name)}.ts`;
  const filepath = path.join(dir, filename);
  
  const header = `// Auto-generated by ZEUS Skill Creator
// Version: ${skill.version}
// Created: ${new Date().toISOString()}

`;
  
  fs.writeFileSync(filepath, header + skill.code);
  
  console.log('💾 SKILL: Salvato', filepath);
  
  return {
    ...skill,
    id: `skill_${Date.now()}`,
    created_at: new Date().toISOString(),
  };
}

export async function listSavedSkills(): Promise<GeneratedSkill[]> {
  const fs = await import('fs');
  const path = await import('path');
  
  const dir = path.join(process.cwd(), SKILLS_DIR);
  if (!fs.existsSync(dir)) {
    return [];
  }
  
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.ts'));
  
  return files.map(filename => {
    const filepath = path.join(dir, filename);
    const content = fs.readFileSync(filepath, 'utf-8');
    
    return {
      id: filename.replace('.ts', ''),
      name: filename.replace('.ts', ''),
      code: content,
      version: 'v0',
      created_at: fs.statSync(filepath).mtime.toISOString(),
    };
  });
}

export async function pushSkillToGit(skill: GeneratedSkill): Promise<{ success: boolean; error?: string }> {
  try {
    const { execSync } = await import('child_process');
    
    process.chdir(process.cwd());
    
    execSync(`git add src/lib/mcp/skills/${skill.name}.ts`, { stdio: 'pipe' });
    execSync(`git commit -m "feat(skill): add ${skill.name} by ZEUS"`, { stdio: 'pipe' });
    
    console.log('🚀 GIT: Skill pushata', skill.name);
    
    return { success: true };
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    console.log('🚀 GIT: Errore push', msg);
    return { success: false, error: msg };
  }
}

export async function loadSkillForExecution(name: string): Promise<string | null> {
  const fs = await import('fs');
  const path = await import('path');
  
  const filepath = path.join(process.cwd(), SKILLS_DIR, `${normalizeSkillName(name)}.ts`);
  
  if (!fs.existsSync(filepath)) {
    return null;
  }
  
  return fs.readFileSync(filepath, 'utf-8');
}