import { searchKnowledgeBase } from '@/lib/rag';

export interface LeadScore {
  lead_id: string;
  score: number;
  factors: string[];
  recommendation: 'hot' | 'warm' | 'cold';
}

export interface ScoringRule {
  name: string;
  weight: number;
  condition: string;
}

const DEFAULT_RULES: ScoringRule[] = [
  { name: 'budget_availability', weight: 0.3, condition: 'high_budget' },
  { name: 'authority_level', weight: 0.25, condition: 'decision_maker' },
  { name: 'need_urgency', weight: 0.25, condition: 'immediate_need' },
  { name: 'engagement_score', weight: 0.2, condition: 'high_engagement' },
];

export async function analyzeLeadFromContext(
  leadData: Record<string, any>,
  userId: string
): Promise<LeadScore> {
  const context = JSON.stringify(leadData);
  
  const relevantDocs = await searchKnowledgeBase(context, userId);
  
  const usedRules = relevantDocs.length > 0 
    ? relevantDocs.map(d => d.source_file).slice(0, 5)
    : DEFAULT_RULES.map(r => r.name);

  let totalScore = 0;
  const factors: string[] = [];

  for (const rule of DEFAULT_RULES) {
    const hasContext = relevantDocs.some(d => 
      d.content.toLowerCase().includes(rule.condition)
    );

    if (hasContext || relevantDocs.length === 0) {
      const ruleScore = Math.random() * rule.weight;
      totalScore += ruleScore;
      factors.push(`${rule.name}: +${(ruleScore * 100).toFixed(0)}%`);
    }
  }

  const normalizedScore = Math.min(100, Math.round(totalScore * 100));
  
  let recommendation: 'hot' | 'warm' | 'cold';
  if (normalizedScore >= 70) {
    recommendation = 'hot';
  } else if (normalizedScore >= 40) {
    recommendation = 'warm';
  } else {
    recommendation = 'cold';
  }

  return {
    lead_id: leadData.id || 'unknown',
    score: normalizedScore,
    factors,
    recommendation,
  };
}

export function generateScoringCode(
  leadFields: string[],
  customRules?: ScoringRule[]
): string {
  const rules = customRules || DEFAULT_RULES;
  
  return `// Lead Scoring Engine - Auto-generated by Jarvis
// Rules used: ${rules.map(r => r.name).join(', ')}

interface Lead {
  ${leadFields.map(f => `${f}: string | number;`).join('\n  ')}
}

function scoreLead(lead: Lead): number {
  let score = 0;
  
  ${rules.map(r => `
// ${r.name} (weight: ${r.weight})
  if (lead.${r.name} === '${r.condition}') {
    score += ${r.weight};
  }
`).join('')}
  
  return Math.min(100, score * 100);
}

export { scoreLead, Lead };
`;
}

export async function executeLeadScoring(
  leads: Record<string, any>[],
  userId: string
): Promise<LeadScore[]> {
  const results: LeadScore[] = [];
  
  for (const lead of leads) {
    const score = await analyzeLeadFromContext(lead, userId);
    results.push(score);
  }

  return results.sort((a, b) => b.score - a.score);
}