-- Core Schema for Multi-Tenant Supabase Setup
-- Migration: 0000_core_schema.sql

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Tenants table
CREATE TABLE IF NOT EXISTS public.tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Profiles table (links auth.users to tenants)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(id, tenant_id)
);

-- Create index on profiles.tenant_id for performance
CREATE INDEX IF NOT EXISTS idx_profiles_tenant_id ON public.profiles(tenant_id);

-- Enable Row Level Security
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Tenants: allow read for authenticated users
CREATE POLICY "Allow read access to authenticated users" ON public.tenants
    FOR SELECT TO authenticated
    USING (true);

-- Tenants: allow service rolefull insert
CREATE POLICY "Allow service role to insert tenants" ON public.tenants
    FOR INSERT TO service_role
    WITH CHECK (true);

-- Tenants: allow service role to update
CREATE POLICY "Allow service role to update tenants" ON public.tenants
    FOR UPDATE TO service_role
    USING (true);

-- Profiles: users can read their own profile
CREATE POLICY "Users can read own profile" ON public.profiles
    FOR SELECT TO authenticated
    USING (auth.uid() = id);

-- Profiles: users can insert their own profile (with tenant_id validation via app)
CREATE POLICY "Users can insert own profile" ON public.profiles
    FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = id);

-- Profiles: users can update their own profile
CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE TO authenticated
    USING (auth.uid() = id);

-- Function to get user's tenant_id from profiles
CREATE OR REPLACE FUNCTION public.user_tenant_id()
RETURNS BIGINT AS $$
    SELECT tenant_id
    FROM public.profiles
    WHERE id = auth.uid()
    LIMIT 1;
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

-- Insert default tenant Manipura (id = 0)
INSERT INTO public.tenants (id, name) VALUES (0, 'Manipura')
ON CONFLICT (id) DO NOTHING;

-- Function to auto-create profile on user signup (trigger)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, tenant_id)
    VALUES (NEW.id, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to auto-create profile after signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();